# Generated by Django 4.2 on 2024-08-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_shipping_invoice_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='country',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='state',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='zipcode',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
