# Generated by Django 4.2 on 2024-08-25 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_shipping_country_shipping_state_shipping_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='shipping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='orders.shipping'),
        ),
    ]
